a= int(input("Enter an integer: "))
b= int(input("Enter an integer: "))
print("left shift: " ,a<<b)
print("right shift: " ,a>>b)
print("AND: " ,a&b)
print("OR: " ,a|b)
print("XOR: " ,a^b)
print("NOT: " , ~a)
print("NOT: " , ~b)
